In [1]:
import os, warnings, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [19]:
dataset =pd.read_csv('/content/drive/MyDrive/master-iot-data/dataset/merged_data.csv')
data = dataset.copy()
data

<ipython-input-19-5f5af92206f1>:1: DtypeWarning: Columns (81,82,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset =pd.read_csv('/content/drive/MyDrive/master-iot-data/dataset/merged_data.csv')

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,Attack Type
0,0,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,256,...,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN,Aggressive Scan
1,1,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,993,...,IMAPS,Email,1,1,NaN,NaN,NaN,NaN,NaN,Aggressive Scan
2,2,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,139,...,NetBIOS,System,1,1,NaN,NaN,NaN,NaN,NaN,Aggressive Scan
3,3,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,143,...,IMAP,Email,1,1,NaN,NaN,NaN,NaN,NaN,Aggressive Scan
4,4,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,135,...,RPC,RPC,1,1,NaN,NaN,NaN,NaN,NaN,Aggressive Scan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547835,3461,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,58124,192.168.137.15,0c:8b:95:09:c6:08,0c:8b:95,80,...,HTTP.Microsoft,Cloud,0,6,espressif.mshome.net,NaN,NaN,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,Vulnerability Scan
547836,3462,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,58134,192.168.137.15,0c:8b:95:09:c6:08,0c:8b:95,80,...,HTTP.Microsoft,Cloud,0,6,espressif.mshome.net,NaN,NaN,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,Vulnerability Scan
547837,3463,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,58142,192.168.137.15,0c:8b:95:09:c6:08,0c:8b:95,80,...,HTTP.Microsoft,Cloud,0,6,espressif.mshome.net,NaN,NaN,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,Vulnerability Scan
547838,3464,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,58158,192.168.137.15,0c:8b:95:09:c6:08,0c:8b:95,80,...,HTTP,Web,0,6,NaN,NaN,NaN,NaN,NaN,Vulnerability Scan
547839,3465,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,58166,192.168.137.15,0c:8b:95:09:c6:08,0c:8b:95,80,...,HTTP.Microsoft,Cloud,0,6,espressif.mshome.net,NaN,NaN,NaN,NaN,Vulnerability Scan

In [20]:
print("Gözlem sayısı : " ,len(data))
print("Değişken sayısı : ", len(data.columns))

Gözlem sayısı :  547840
Değişken sayısı :  87

In [21]:
data['Attack Type'].value_counts()

Attack Type
SYN Flood             131107
Synonymous IP         131093
TCP Flood             131087
Push ACK Flood         65536
UDP Flood              15956
SYN Stealth            15247
Port Scan              13092
Vulnerability Scan     12581
Aggressive Scan        12332
OS Fingerprinting       8381
Service Detection       7141
SlowLoris Scan          4201
Benign                    68
ICMP Fragmentation        16
ICMP Flood                 2
Name: count, dtype: int64

NaN ve Inf Değerleri Kontrol Etme

In [22]:
#NaN değere sahip sutünları kaldırma
data.drop(["requested_server_name","client_fingerprint","server_fingerprint","user_agent","content_type"],axis=1,inplace=True)

In [23]:

non_integer_columns = data.select_dtypes(exclude=['int']).columns
print("Non-integer columns:", non_integer_columns)

Non-integer columns: Index(['src_ip', 'src_mac', 'src_oui', 'dst_ip', 'dst_mac', 'dst_oui',
       'bidirectional_mean_ps', 'bidirectional_stddev_ps', 'src2dst_mean_ps',
       'src2dst_stddev_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms',
       'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms', 'application_name',
       'application_category_name', 'Attack Type'],
      dtype='object')

In [24]:
data['bidirectional_mean_ps'] = data['bidirectional_mean_ps'].round().astype(int)
data['bidirectional_stddev_ps'] = data['bidirectional_stddev_ps'].round().astype(int)
data['src2dst_mean_ps'] = data['src2dst_mean_ps'].round().astype(int)
data['src2dst_stddev_ps'] = data['src2dst_stddev_ps'].round().astype(int)
data['dst2src_mean_ps'] = data['dst2src_mean_ps'].round().astype(int)
data['dst2src_stddev_ps'] = data['dst2src_stddev_ps'].round().astype(int)
data['bidirectional_mean_piat_ms'] = data['bidirectional_mean_piat_ms'].round().astype(int)
data['bidirectional_stddev_piat_ms'] = data['bidirectional_stddev_piat_ms'].round().astype(int)
data['src2dst_mean_piat_ms'] = data['src2dst_mean_piat_ms'].round().astype(int)
data['src2dst_stddev_piat_ms'] = data['src2dst_stddev_piat_ms'].round().astype(int)
data['dst2src_mean_piat_ms'] = data['dst2src_mean_piat_ms'].round().astype(int)
data['dst2src_stddev_piat_ms'] = data['dst2src_stddev_piat_ms'].round().astype(int)

In [25]:
data['Attack Type'].value_counts()

Attack Type
SYN Flood             131107
Synonymous IP         131093
TCP Flood             131087
Push ACK Flood         65536
UDP Flood              15956
SYN Stealth            15247
Port Scan              13092
Vulnerability Scan     12581
Aggressive Scan        12332
OS Fingerprinting       8381
Service Detection       7141
SlowLoris Scan          4201
Benign                    68
ICMP Fragmentation        16
ICMP Flood                 2
Name: count, dtype: int64

In [26]:
attack_types = data['Attack Type'].unique()
print(attack_types)

['Aggressive Scan' 'ICMP Flood' 'ICMP Fragmentation' 'OS Fingerprinting'
 'Port Scan' 'Push ACK Flood' 'Service Detection' 'SlowLoris Scan'
 'SYN Flood' 'SYN Stealth' 'Synonymous IP' 'TCP Flood' 'UDP Flood'
 'Vulnerability Scan' 'Benign']

In [27]:
group = { 'Benign': 0,
          'SYN Flood': 1,
          'Synonymous IP': 2,
          'TCP Flood': 3,
          'Push ACK Flood': 4,
          'UDP Flood': 5,
          'SYN Stealth': 6,
          'Port Scan': 7,
          'Vulnerability Scan': 8,
          'Aggressive Scan': 9,
          'OS Fingerprinting': 10,
          'Service Detection': 11,
          'SlowLoris Scan': 12,
          'ICMP Fragmentation': 13,
          'ICMP Flood': 14}



data['Attack_Num'] = dataset['Attack Type'].map(lambda x: group[x])
data['Attack_Num'].value_counts()

Attack_Num
1     131107
2     131093
3     131087
4      65536
5      15956
6      15247
7      13092
8      12581
9      12332
10      8381
11      7141
12      4201
0         68
13        16
14         2
Name: count, dtype: int64

In [28]:
# Attack_Num sütununda değeri 13 veya 14 olan satırları seçin
rows_to_drop = data[(data['Attack_Num'] == 13) | (data['Attack_Num'] == 14)   ].index

# Seçilen satırları veri çerçevesinden silin
data.drop(rows_to_drop, inplace=True)

# Silme işleminden sonra veri çerçevesini yeniden indeksleyin
data.reset_index(drop=True, inplace=True)

In [29]:
data['Attack_Num'].value_counts()

Attack_Num
1     131107
2     131093
3     131087
4      65536
5      15956
6      15247
7      13092
8      12581
9      12332
10      8381
11      7141
12      4201
0         68
Name: count, dtype: int64

In [30]:
#Label_Num = Label , Cat_Num = Cat , Sub_Cat_Num = Sub_Cat
data.drop(["Attack Type"],axis=1,inplace=True)

In [31]:
columns_to_drop = ['id','expiration_id', 'src_port' , 'dst_port','src_ip', 'dst_ip', 'src_mac', 'dst_mac', 'src_oui', 'dst_oui', 'application_category_name' , 'application_name']
data.drop(columns=columns_to_drop, inplace=True)

In [32]:
non_integer_columns = data.select_dtypes(exclude=['int']).columns
print("Non-integer columns:", non_integer_columns)

Non-integer columns: Index([], dtype='object')

In [33]:
data.to_csv("/content/drive/MyDrive/master-iot-data/cleaned_merged_data.csv", index = False)

In [34]:
from sklearn.preprocessing import MinMaxScaler

# Min-Max normalizasyonu için bir ölçekleyici oluşturun
scaler = MinMaxScaler()

# 'atack_num' sütununu dışındaki veri sütunlarını ölçeklendirin
scaled_data = data.copy()  # Veriyi korumak için kopyalayın
columns_to_scale = scaled_data.columns.difference(['Attack_Num'])  # 'atack_num' sütunu dışındaki sütunları seçin
scaled_data[columns_to_scale] = scaler.fit_transform(scaled_data[columns_to_scale])  # Seçilen sütunları ölçeklendirin

# Normalleştirilmiş veriyi görüntüleyin
print(scaled_data.head())
data = scaled_data.copy()

   protocol  ip_version  vlan_id  tunnel_id  bidirectional_first_seen_ms  \
0  0.087719         0.0      0.0        0.0                     0.683319
1  0.087719         0.0      0.0        0.0                     0.683319
2  0.087719         0.0      0.0        0.0                     0.683319
3  0.087719         0.0      0.0        0.0                     0.683319
4  0.087719         0.0      0.0        0.0                     0.683319

   bidirectional_last_seen_ms  bidirectional_duration_ms  \
0                    0.681626                   0.000063
1                    0.681626                   0.000065
2                    0.681626                   0.000065
3                    0.681626                   0.000066
4                    0.681626                   0.000066

   bidirectional_packets  bidirectional_bytes  src2dst_first_seen_ms  ...  \
0               0.000003             0.000002               0.683319  ...
1               0.000003             0.000002               0.683319  ...
2               0.000003             0.000002               0.683319  ...
3               0.000003             0.000002               0.683319  ...
4               0.000003             0.000002               0.683319  ...

   dst2src_cwr_packets  dst2src_ece_packets  dst2src_urg_packets  \
0                  0.0                  0.0                  0.0
1                  0.0                  0.0                  0.0
2                  0.0                  0.0                  0.0
3                  0.0                  0.0                  0.0
4                  0.0                  0.0                  0.0

   dst2src_ack_packets  dst2src_psh_packets  dst2src_rst_packets  \
0             0.001724                  0.0                  0.2
1             0.001724                  0.0                  0.2
2             0.001724                  0.0                  0.2
3             0.001724                  0.0                  0.2
4             0.001724                  0.0                  0.2

   dst2src_fin_packets  application_is_guessed  application_confidence  \
0                  0.0                     0.0                0.000000
1                  0.0                     1.0                0.166667
2                  0.0                     1.0                0.166667
3                  0.0                     1.0                0.166667
4                  0.0                     1.0                0.166667

   Attack_Num
0           9
1           9
2           9
3           9
4           9

[5 rows x 70 columns]

In [35]:
data.to_csv("/content/drive/MyDrive/master-iot-data/cleaned_merged_data_MinMax.csv", index = False)